[package]
name = "lyrae-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "^1.8.0"
bytemuck = "^1.7.2"